<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Archon.Application\Archon.Application.csproj" />
    <ProjectReference Include="..\Archon.Extractors\Archon.Extractors.csproj" />
    <ProjectReference Include="..\Archon.Infrastructure.Roslyn\Archon.Infrastructure.Roslyn.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>
