using Archon.Roslyn.Legacy;
using Xunit;

namespace Archon.Roslyn.Legacy.Tests
{
    /// <summary>
    /// Verifies legacy and generated-code source classification helpers used by degraded Roslyn extraction.
    /// </summary>
    public sealed class LegacyGeneratedCodeClassifierTests
    {
        /// <summary>
        /// Confirms that generated file-name conventions are detected without reading source text.
        /// </summary>
        [Fact]
        public void IsGeneratedFileRecognizesGeneratedFileNamePatterns()
        {
            // Legacy .NET repositories often contain designer and generated files whose names are more reliable than project metadata.
            Assert.True(LegacyGeneratedCodeClassifier.IsGeneratedFile("src/Sample/Resources.Designer.cs", sourceHeader: null));
            Assert.True(LegacyGeneratedCodeClassifier.IsGeneratedFile("src/Sample/View.g.vb", sourceHeader: null));
            Assert.True(LegacyGeneratedCodeClassifier.IsGeneratedFile("src/Sample/Widget.generated.cs", sourceHeader: null));
            Assert.False(LegacyGeneratedCodeClassifier.IsGeneratedFile("src/Sample/Widget.cs", sourceHeader: null));
        }

        /// <summary>
        /// Confirms that auto-generated headers are detected even when the file name looks hand-maintained.
        /// </summary>
        [Fact]
        public void IsGeneratedFileRecognizesGeneratedHeaders()
        {
            // Some source generators and legacy tools keep ordinary file names but write deterministic generated headers at the top of the file.
            string header = "// <auto-generated />\n// Generated by SampleTool";

            Assert.True(LegacyGeneratedCodeClassifier.IsGeneratedFile("src/Sample/Widget.cs", header));
        }

        /// <summary>
        /// Confirms that generated files receive deterministic metadata used by language extractors and future graph persistence.
        /// </summary>
        [Fact]
        public void CreateGeneratedMetadataReturnsDeterministicFields()
        {
            // The metadata helper mirrors the source-classification vocabulary used by the shared semantic model.
            IReadOnlyDictionary<string, string> metadata = LegacyGeneratedCodeClassifier.CreateGeneratedMetadata("src/Sample/View.Designer.vb", generated: true);

            Assert.Equal("true", metadata["generated"]);
            Assert.Equal("LegacyGeneratedCodeClassifier", metadata["classifier"]);
            Assert.Equal("src/Sample/View.Designer.vb", metadata["sourcePath"]);
        }
    }
}
