namespace Archon.Roslyn.Legacy
{
    /// <summary>
    /// Classifies legacy source files that are likely generated by designers, source generators, or older .NET tooling.
    /// </summary>
    /// <remarks>
    /// The classifier complements the shared Roslyn generated-code detector with a small dependency-free API that legacy and degraded extraction tests can use without constructing syntax trees.
    /// </remarks>
    public static class LegacyGeneratedCodeClassifier
    {
        /// <summary>
        /// Determines whether a source path and optional header indicate generated code.
        /// </summary>
        /// <param name="sourcePath">The repository-relative or absolute source path to inspect.</param>
        /// <param name="sourceHeader">The optional leading source text or header comments to inspect.</param>
        /// <returns><see langword="true" /> when deterministic generated-code signals are present.</returns>
        public static bool IsGeneratedFile(string sourcePath, string? sourceHeader)
        {
            // Legacy repositories commonly expose generated origin through names such as .Designer, .g, or generated folders; headers provide a second deterministic signal.
            string normalizedPath = RequireText(sourcePath, nameof(sourcePath)).Replace('\\', '/');
            return HasGeneratedPathSignal(normalizedPath) || HasGeneratedHeaderSignal(sourceHeader);
        }

        /// <summary>
        /// Creates deterministic metadata describing a legacy generated-code classification decision.
        /// </summary>
        /// <param name="sourcePath">The source path that was classified.</param>
        /// <param name="generated">A value indicating whether the source was classified as generated.</param>
        /// <returns>A read-only metadata dictionary suitable for semantic fact metadata.</returns>
        public static IReadOnlyDictionary<string, string> CreateGeneratedMetadata(string sourcePath, bool generated)
        {
            // The metadata keys intentionally match the shared semantic vocabulary so graph projection can treat legacy and compiler-based classification uniformly.
            string normalizedPath = RequireText(sourcePath, nameof(sourcePath)).Replace('\\', '/');
            return new Dictionary<string, string>(StringComparer.Ordinal)
            {
                ["classifier"] = nameof(LegacyGeneratedCodeClassifier),
                ["generated"] = generated ? "true" : "false",
                ["sourcePath"] = normalizedPath
            };
        }

        /// <summary>
        /// Determines whether a normalized path contains generated-code file or folder conventions.
        /// </summary>
        /// <param name="normalizedPath">The normalized path that uses forward slashes.</param>
        /// <returns><see langword="true" /> when the path contains a generated-code signal.</returns>
        private static bool HasGeneratedPathSignal(string normalizedPath)
        {
            // This list intentionally favors common deterministic .NET naming conventions over broad fuzzy matching.
            string fileName = Path.GetFileName(normalizedPath);
            return fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
                || fileName.EndsWith(".g.vb", StringComparison.OrdinalIgnoreCase)
                || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
                || fileName.EndsWith(".generated.vb", StringComparison.OrdinalIgnoreCase)
                || fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase)
                || fileName.EndsWith(".designer.vb", StringComparison.OrdinalIgnoreCase)
                || normalizedPath.Contains("/generated/", StringComparison.OrdinalIgnoreCase)
                || normalizedPath.Contains("/obj/", StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// Determines whether source header text contains generated-code markers.
        /// </summary>
        /// <param name="sourceHeader">The optional source header text to inspect.</param>
        /// <returns><see langword="true" /> when the header contains an auto-generated marker.</returns>
        private static bool HasGeneratedHeaderSignal(string? sourceHeader)
        {
            // Header inspection is intentionally simple and deterministic because callers may pass only a small leading slice of the source file.
            if (string.IsNullOrWhiteSpace(sourceHeader))
            {
                return false;
            }

            return sourceHeader.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)
                || sourceHeader.Contains("auto generated", StringComparison.OrdinalIgnoreCase)
                || sourceHeader.Contains("auto-generated", StringComparison.OrdinalIgnoreCase)
                || sourceHeader.Contains("generated by", StringComparison.OrdinalIgnoreCase);
        }

        /// <summary>
        /// Requires non-empty classifier text.
        /// </summary>
        /// <param name="value">The text supplied by classifier callers.</param>
        /// <param name="parameterName">The source parameter name used in validation failures.</param>
        /// <returns>The trimmed classifier text.</returns>
        private static string RequireText(string? value, string parameterName)
        {
            // Generated-code classification must know which source path it is explaining.
            if (string.IsNullOrWhiteSpace(value))
            {
                throw new ArgumentException("Legacy generated-code classifier values cannot be null, empty, or whitespace.", parameterName);
            }

            return value.Trim();
        }
    }
}
