<Project Sdk="Aspire.AppHost.Sdk/13.3.3">

  <ItemGroup>
    <ProjectReference Include="..\ArchonApi\ArchonApi.csproj" />
    <ProjectReference Include="..\ArchonMcp\ArchonMcp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.3.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>
