using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Archon.Roslyn.SemanticModel
{
    /// <summary>
    /// Detects source documents that are likely generated by tooling rather than hand-maintained by contributors.
    /// </summary>
    /// <remarks>
    /// Generated-code detection uses deterministic local signals only: file names, source headers, and common generated directory conventions. The helper intentionally avoids environment-specific state.
    /// </remarks>
    public static class SemanticGeneratedCodeDetector
    {
        /// <summary>
        /// Determines whether the supplied syntax tree appears to represent generated code.
        /// </summary>
        /// <param name="syntaxTree">The syntax tree whose path and source header should be inspected.</param>
        /// <param name="cancellationToken">A token that signals when source text access should stop.</param>
        /// <returns><see langword="true" /> when deterministic generated-code signals are present.</returns>
        public static bool IsGenerated(SyntaxTree syntaxTree, CancellationToken cancellationToken = default)
        {
            // The detector treats any strong deterministic signal as sufficient because generated source should be marked rather than hidden.
            ArgumentNullException.ThrowIfNull(syntaxTree);
            string normalizedPath = syntaxTree.FilePath.Replace('\\', '/');
            if (HasGeneratedPathSignal(normalizedPath))
            {
                return true;
            }

            SourceText sourceText = syntaxTree.GetText(cancellationToken);
            int lineCount = Math.Min(sourceText.Lines.Count, 8);
            for (int index = 0; index < lineCount; index++)
            {
                string line = sourceText.Lines[index].ToString();
                if (line.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase)
                    || line.Contains("auto generated", StringComparison.OrdinalIgnoreCase)
                    || line.Contains("auto-generated", StringComparison.OrdinalIgnoreCase)
                    || line.Contains("generated by", StringComparison.OrdinalIgnoreCase))
                {
                    return true;
                }
            }

            return false;
        }

        /// <summary>
        /// Adds generated-code metadata fields to an existing metadata dictionary.
        /// </summary>
        /// <param name="metadata">The metadata dictionary that should receive generated-code fields.</param>
        /// <param name="generated">A value indicating whether the source was classified as generated.</param>
        public static void AddGeneratedMetadata(IDictionary<string, string> metadata, bool generated)
        {
            // Relationship and declaration metadata use string values because graph payloads are serialized as deterministic name/value fields.
            ArgumentNullException.ThrowIfNull(metadata);
            metadata["generated"] = generated ? "true" : "false";
        }

        /// <summary>
        /// Determines whether a normalized path contains generated-code file or folder conventions.
        /// </summary>
        /// <param name="normalizedPath">The normalized path that uses forward slashes.</param>
        /// <returns><see langword="true" /> when the path contains a generated-code signal.</returns>
        private static bool HasGeneratedPathSignal(string normalizedPath)
        {
            // The signal list covers common .NET generated files and folders while remaining deterministic and repository-local.
            string fileName = Path.GetFileName(normalizedPath);
            return fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
                || fileName.EndsWith(".g.vb", StringComparison.OrdinalIgnoreCase)
                || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
                || fileName.EndsWith(".generated.vb", StringComparison.OrdinalIgnoreCase)
                || fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase)
                || fileName.EndsWith(".designer.vb", StringComparison.OrdinalIgnoreCase)
                || normalizedPath.Contains("/generated/", StringComparison.OrdinalIgnoreCase)
                || normalizedPath.Contains("/obj/", StringComparison.OrdinalIgnoreCase);
        }
    }
}
