<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Archon.Application\Archon.Application.csproj" />
    <ProjectReference Include="..\Archon.Roslyn\Archon.Roslyn.csproj" />
    <ProjectReference Include="..\Archon.Roslyn.CSharp\Archon.Roslyn.CSharp.csproj" />
    <ProjectReference Include="..\Archon.Roslyn.VisualBasic\Archon.Roslyn.VisualBasic.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

</Project>
